minidlna: convert to new template

diff --git a/setup.d/minidlna b/setup.d/minidlna
--- a/setup.d/minidlna
+++ b/setup.d/minidlna
@@ -1,23 +1,19 @@
-#!/bin/bash -e
-
-# MiniDLNA
-
+#!/usr/bin/env bash
+# Copyright (C) 2022 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
+# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
 # -----------------------------------------------------------------------------
 
-setuplib=${1:-${SETUP_LIB:-$(dirname "$(readlink -f "$0")")/../setuplib}}
+DESCRIPTION='MiniDLNA Server'
+ARGS='[MEDIA_DIR] [FRIENDLY_NAME]'
 
-usage() { echo "Usage: ${0##*/} [SETUP_LIB]" >&2; exit 1; }
-
-if [[ -r "$setuplib" ]]; then
-	source "$setuplib"
-else
-	echo "Setup library not found! $setuplib" >&2
-	usage
+setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
+# shellcheck source=../setuplib
+if [[ -r "$setuplib" ]]; then source "$setuplib"; else
+	echo "Setup library not found: $setuplib" >&2; exit 1;
 fi
-
 # -----------------------------------------------------------------------------
 
-package_install minidlna
+install_package minidlna
 
 # Fix "WARNING: Inotify max_user_watches [8192] is low ..."
 # https://forum.excito.com/viewtopic.php?t=3592
